name=ESP32httpOTA
version=1.0.0
author=voknetral
maintainer=voknetral
sentence=OTA Firmware Update Engine for ESP32 via HTTP/HTTPS.
paragraph=Lightweight and modular library for performing Over-The-Air firmware updates on ESP32 via any HTTP/HTTPS server. Supports semantic versioning, CA certificate pinning, progress callbacks, configurable timeout, and debug logging. Works with GitHub, VPS, S3, or self-hosted servers.
category=Communication
url=https://github.com/voknetral/ESP32httpOTA
architectures=esp32
depends=ArduinoJson
